// <auto-generated />
using DiscordBotAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscordBotAPI.Migrations
{
    [DbContext(typeof(DiscordBotApiContext))]
    [Migration("20220815085045_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscordBotAPI.Models.DiscordUser", b =>
                {
                    b.Property<string>("DiscordUserId")
                        .HasColumnType("text")
                        .HasColumnName("discorduserid");

                    b.Property<string>("OneCGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onecguid");

                    b.HasKey("DiscordUserId");

                    b.ToTable("detail");
                });
#pragma warning restore 612, 618
        }
    }
}
